version: "3.8"

services:
  dn:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: dn
    hostname: dn
    environment:
      - CORE_CONF_fs_defaultFS=${HDFS_NAMENODE_URI}
      - HDFS_CONF_dfs_replication=2
      - SERVICE_PRECONDITION=${HDFS_NAMENODE_IP}:9870
      # 필요 시 고정 광고 주소
      # - HDFS_CONF_dfs_datanode_hostname=${WORKER_HOST_IP}
    volumes:
      - ./hadoop/conf:/opt/hadoop/etc/hadoop
      - datanode:/hadoop/dfs/data
    restart: unless-stopped

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    volumes:
      - ./spark/conf:/opt/bitnami/spark/conf
    restart: unless-stopped

volumes:
  datanode: